### ISSUE TITLE
ast: comma separated list is parsed as empty (even when present in input)

### ISSUE THREAD

**Issue by mewmew** [inspirer/textmapper#24]
Using the parser generated by the latest revision of Textmapper (c3f3e1be60b03c82eea22a8dccffc0b134153c65), I've run into a bug where the AST `Indices` method of `GetElementPtrInst` instructions return an empty slice, even when the input text contains indices.

Given the following input text [inst_memory.ll](https://github.com/mewspring/foo/blob/master/indices/inst_memory.ll):

**Note:** in the input text below `, i64 0, i64 0` corresponds to the list of indices (where `i64 0` is reduced as a `TypeValue`).

```llvm
@s = constant [4 x i8] c"foo\00"

define void @f() {
	%1 = getelementptr [4 x i8], [4 x i8]* @s, i64 0, i64 0
	ret void
}
```

And the relevant parts of the grammar [ll.tm](https://github.com/llir/grammar/blob/3258584057ea2fd1599886377519c27955d32ed6/ll.tm#L2289):

```c
GetElementPtrInst -> GetElementPtrInst
	: 'getelementptr' InBoundsopt ElemType=Type ',' Src=TypeValue Indices=(',' TypeValue)* Metadata=(',' MetadataAttachment)+?
;
```

To reproduce the above observation, run the following commands.

```bash
$ go get -u github.com/mewspring/foo/indices
$ cd $GOPATH/src/github.com/mewspring/foo/indices/cmd/indices
$ go run main.go inst_memory.ll
text: "getelementptr [4 x i8], [4 x i8]* @s, i64 0, i64 0"
elem type: "[4 x i8]"
src: "[4 x i8]* @s"
len(indices): 0
```

The expected output is `len(indices): 2`. So, for some reason, the indices is not present in the AST.

Note, no changes have been made to the generated parser, which is located at https://github.com/llir/ll

The only hand-written code is that of [main.go](https://github.com/mewspring/foo/blob/master/indices/main.go)

**Comment by mewmew** [comment]
A minimal reproducible example has been created where this issue is exhibited.

Given the following grammar [issue24.tm](https://github.com/mewspring/foo/blob/master/issue24/issue24.tm):

```c
language issue24(go);

lang = "issue24"
package = "github.com/mewspring/foo/issue24"
eventBased = true
eventFields = true
eventAST = true

:: lexer

id_tok : /[a-z]/
'gep' : /gep/
',' : /,/

whitespace : /[ \t\r\n]+/     (space)

:: parser

%input Foo;

Foo -> Foo
   : 'gep' Src=ID Indices=(',' ID)*
;

ID -> ID
   : id_tok
;
```

And the following input text [input.txt](https://github.com/mewspring/foo/blob/master/issue24/cmd/issue24/input.txt):

```
gep a, b, c
```

Run the following set of commands to reproduce the issue:

```bash
$ go get -u github.com/mewspring/foo/issue24/cmd/issue24
$ cd $GOPATH/src/github.com/mewspring/foo/issue24/cmd/issue24
$ issue24 input.txt
Src: a
len(Indices): 0
```

Expected output `len(Indices): 2`, got `len(Indices): 0`.

**Comment by inspirer** [comment]
Many thanks for the repro case! I'll fix this.
