### ISSUE TITLE
jar: error while generating a sublexer that matches {eoi} as invalid_token

### ISSUE THREAD

**Issue by nazavode** [inspirer/textmapper#34]
While trying to generate the Go lexer via `textmapper.jar` (`master` `@` 08d03f47fd316ba9c1a4d8a4af9bc7e3b7a3fbac compiled with `openjdk version "13.0.1" 2019-10-15`), I got the following error:

```console
$ ls
test.tm
$ java -jar textmapper.jar
jar:file:textmapper.jar!/org/textmapper/tool/templates/go_token.ltp,19: Evaluation of `syntax.symbols[i].isConstant()` failed for [common.Context]: (caused by java.lang.IllegalArgumentException): null
jar:file:textmapper.jar!/org/textmapper/tool/templates/go_token.ltp,28: Evaluation of `syntax.symbols[i].isConstant()` failed for [common.Context]: (caused by java.lang.IllegalArgumentException): null
lalr: 0.009s, text: 0.146s
```

The grammar that triggers the issue (reduced to a minimal reproducer) is:

```
language test(go);
lang = "test"

:: lexer

%s initial;
%x inComment;

invalid_token:
error:

whitespace: /[\n\r\t\f\v ]+/ (space)

<initial, inComment> EnterBlockComment:  /\(\*/ (space)

<initial> invalid_token: /\*\)/

<inComment> {
invalid_token: /{eoi}/
ExitBlockComment: /\*\)/ (space)
BlockComment: /[^\(\)\*]+|[\*\(\)]/ (space)
}
```

The issue seems to be triggered by `<inComment> invalid_token: /{eoi}/`: I'm assuming the rule is allowed since compiling the same grammar with `tm-go/cmd/textmapper` works perfectly.

**Comment by inspirer** [comment]
Thanks for reporting!

**Comment by nazavode** [comment]
Thanks to you for the amazing project! I still have to look into parser generation but as far as I'm using the lexer part I think textmapper is by far the best one available for Go. Still in the process of learning Go but I hope to be able to contribute at some point.
